<?php include 'templates/layout/html-upper-jh.phtml'; ?>

    <!------------------------------------------------------>
    <!----------------- MAIN HTML CONTENT  ----------------->
    <!------------------------------------------------------>
    <div data-layout="row" data-layout-align="center center">
        <!-- LEFT side -->
        <div data-layout-padding data-flex="25">
            <h4>Hi. I'm Julius Alvarado.</h4>

            <!-- icon about -->
            <div data-layout="column" data-layout-align="center center">
                <ng-md-icon icon="face" style="fill: #723d0f" size="36"></ng-md-icon>
                <h5>
                    I'm a Senior-level Fullstack Web Engineer & Mid-level Data Engineer that uses PHP, SQL, & JS/Node
                </h5>
            </div>

            <h3>Talent:</h3>
            <h1 class="cb-text-center cb-mtop-0">
                10 / 10
                <ng-md-icon icon="check_circle" style="fill: hotpink"></ng-md-icon>
            </h1>
        </div>

        <!-- RIGHT side -->
        <div class="md-padding" data-flex="60">
            <h1>My primary tool for fullstack web & data engineering is PHP.</h1>
            <p>
                Here are <b>Examples</b> of the classes, functions, techniques, and core features of PHP I use:
            </p>
            <ul>
                <li><a href="/julius/basics">Programming Fundamentals</a></li>
                <li><a href="/julius/oop">Object Oriented Programming</a></li>
                <li><a href="/julius/security">Web Application Security</a></li>
                <li><a href="/julius/arrays">Arrays & Data Structures</a></li>
                <li><a href="/julius/strings">Strings & The Regex Engine</a></li>
                <li><a href="/julius/functions">Functional Programming</a></li>
                <li><a href="/julius/web">Built-in Web Features of PHP</a></li>
                <li><a href="/julius/data">Data Services & Data Types/Formats</a></li>
                <li><a href="/julius/errors">Error Handling</a></li>
                <li><a href="/julius/sql">SQL & Database Systems</a></li>
                <li><a href="/julius/io">io (Input Output)</a></li>
                <li><a href="/julius/testing">Unit Testing</a></li>
            </ul>

            <br>

            <p>
                <small>
                    ... These past couple of years I've been using mostly native PHP (no frameworks),
                    heavy duty Computer Science, and some AngularJS to build on-premise intrAnet based data applications
                    and automated data processing systems. I'm currently in the process of adding Laravel, React,
                    & BigQuery(for big data) to my skill set as well.
                </small>
            </p>
        </div>
    </div>

    <br>

<?php include 'templates/layout/html-lower-jh.phtml'; ?>