<?php include 'templates/layout/html-upper-jh.phtml'; ?>

    <div data-layout="column" data-layout-align="center center" class="ja-topic-hero">
        <h2>Examples of <i>Functional Programming</i></h2>
        <p>
            Based on my studies, practice, & <b>work experience</b> <br>
            <small>( ⚠ = In-progress,  🏃‍♂️ = Quick Example,  ✅ = Thorough Example )</small>
        </p>
    </div>

    <!-- AngularJS Dynamic Tabs -->
    <div ng-controller="functionsCtrl" layout="column" ng-cloak class="jaDynamicTabs">
        <md-content class="md-padding">
            <md-tabs md-selected="selectedIndex" md-dynamic-height md-border-bottom md-autoselect md-swipe-content>
                <md-tab ng-repeat="tab in tabs" ng-disabled="tab.disabled" label="{{tab.title}}">
                    <!-- The Actual tab content -->
                    <section class="tab{{$index%4}}" layout="column"
                             layout-align="center center" layout-padding
                             layout-margin ng-bind-html="tab.content">
                    </section>
                </md-tab>
            </md-tabs>
        </md-content>
    </div>

    <br>
<?php include 'templates/layout/html-lower-jh.phtml'; ?>