<!DOCTYPE html>

<?php
include 'templates/layout/html-upper.php';
//<!-- Horizontal sort of Nav Bar -->
include 'templates/layout/toolbar.php';
?>

<!-- _SESSION TEST -->
{{status}}
<br>
<?= $_SESSION['c_user_id'] ?? 'no Hack Match user with an id' ?>


<!------------------------------------------------------>
<!----------------- MAIN HTML CONTENT  ----------------->
<!------------------------------------------------------>
<div class="landing">
    <h1>Your Matches</h1>
    <h4>Click on their profiles to learn more! ^_^</h4>
    
    <?php if(isset($name)) : ?>
        <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
    <?php else: ?>
        <p><a href="/test/get-matched">Home</a></p>
    <?php endif; ?>

    

    <md-content class="md-padding" layout-xs="column" layout="row" layout-wrap>
        <!-- Card 1 -->
        <div flex-xs flex-gt-xs="25">
            <md-card>
                <!-- Avatar Header -->
                <md-card-header>
                    <md-card-avatar>
                        <img class="md-user-avatar" ng-src="{{s_avatarImg}}">
                    </md-card-avatar>
                    <md-card-header-text>
                        <span class="md-title">User</span>
                        <span class="md-subhead">match</span>
                    </md-card-header-text>
                </md-card-header>

                <!-- Hero Image, one day it should be of the matched user -->
                <img ng-src="{{s_imgPath}}" class="md-card-image" alt="Washed Out">

                <!-- The Card Title -->
                <md-card-title>
                    <md-card-title-text>
                        <span class="md-headline">Your Hack Match</span>
                        <span class="md-subhead">Now reach out! <ng-md-icon icon="rowing"></ng-md-icon></span>
                    </md-card-title-text>
                </md-card-title>

                <!-- Action Buttons -->
                <md-card-actions layout="row" layout-align="start center">
                    <md-button>Profile</md-button>
                    <!-- <md-button>More Info</md-button> -->
                    <md-card-icon-actions>
                        <md-button class="md-icon-button" aria-label="Favorite">
                            <md-icon md-svg-icon="/img/icons/favorite.svg"></md-icon>
                        </md-button>
                        <md-button class="md-icon-button" aria-label="Share">
                            <md-icon md-svg-icon="/img/icons/baseline-share-24px.svg"></md-icon>
                        </md-button>
                    </md-card-icon-actions>
                </md-card-actions>

                <!-- Card Content, more of the match info can go here -->
                <md-card-content>
                    <p>
                        The titles of Washed Out's breakthrough song and the first single from Paracosm share the
                        two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
                    </p>
                </md-card-content>
            </md-card>
        </div>
        <!-- Card 2 -->
        <div flex-xs flex-gt-xs="25">
            <md-card>
                <!-- Avatar Header -->
                <md-card-header>
                    <md-card-avatar>
                        <img class="md-user-avatar" ng-src="{{s_avatarImg}}">
                    </md-card-avatar>
                    <md-card-header-text>
                        <span class="md-title">User</span>
                        <span class="md-subhead">match</span>
                    </md-card-header-text>
                </md-card-header>

                <!-- Hero Image, one day it should be of the matched user -->
                <img ng-src="{{s_imgPath}}" class="md-card-image" alt="Washed Out">

                <!-- The Card Title -->
                <md-card-title>
                    <md-card-title-text>
                        <span class="md-headline">Your Hack Match</span>
                        <span class="md-subhead">Now reach out! <ng-md-icon icon="rowing"></ng-md-icon></span>
                    </md-card-title-text>
                </md-card-title>

                <!-- Action Buttons -->
                <md-card-actions layout="row" layout-align="start center">
                    <md-button>Profile</md-button>
                    <!-- <md-button>More Info</md-button> -->
                    <md-card-icon-actions>
                        <md-button class="md-icon-button" aria-label="Favorite">
                            <md-icon md-svg-icon="/img/icons/favorite.svg"></md-icon>
                        </md-button>
                        <md-button class="md-icon-button" aria-label="Share">
                            <md-icon md-svg-icon="/img/icons/baseline-share-24px.svg"></md-icon>
                        </md-button>
                    </md-card-icon-actions>
                </md-card-actions>

                <!-- Card Content, more of the match info can go here -->
                <md-card-content>
                    <p>
                        The titles of Washed Out's breakthrough song and the first single from Paracosm share the
                        two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
                    </p>
                </md-card-content>
            </md-card>
        </div>
        <!-- Card 3 -->
        <div flex-xs flex-gt-xs="25">
            <md-card>
                <!-- Avatar Header -->
                <md-card-header>
                    <md-card-avatar>
                        <img class="md-user-avatar" ng-src="{{s_avatarImg}}">
                    </md-card-avatar>
                    <md-card-header-text>
                        <span class="md-title">User</span>
                        <span class="md-subhead">match</span>
                    </md-card-header-text>
                </md-card-header>

                <!-- Hero Image, one day it should be of the matched user -->
                <img ng-src="{{s_imgPath}}" class="md-card-image" alt="Washed Out">

                <!-- The Card Title -->
                <md-card-title>
                    <md-card-title-text>
                        <span class="md-headline">Your Hack Match</span>
                        <span class="md-subhead">Now reach out! <ng-md-icon icon="rowing"></ng-md-icon></span>
                    </md-card-title-text>
                </md-card-title>

                <!-- Action Buttons -->
                <md-card-actions layout="row" layout-align="start center">
                    <md-button>Profile</md-button>
                    <!-- <md-button>More Info</md-button> -->
                    <md-card-icon-actions>
                        <md-button class="md-icon-button" aria-label="Favorite">
                            <md-icon md-svg-icon="/img/icons/favorite.svg"></md-icon>
                        </md-button>
                        <md-button class="md-icon-button" aria-label="Share">
                            <md-icon md-svg-icon="/img/icons/baseline-share-24px.svg"></md-icon>
                        </md-button>
                    </md-card-icon-actions>
                </md-card-actions>

                <!-- Card Content, more of the match info can go here -->
                <md-card-content>
                    <p>
                        The titles of Washed Out's breakthrough song and the first single from Paracosm share the
                        two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
                    </p>
                </md-card-content>
            </md-card>
        </div>
        <!-- Card 4 -->
        <div flex-xs flex-gt-xs="25">
            <md-card>
                <!-- Avatar Header -->
                <md-card-header>
                    <md-card-avatar>
                        <img class="md-user-avatar" ng-src="{{s_avatarImg}}">
                    </md-card-avatar>
                    <md-card-header-text>
                        <span class="md-title">User</span>
                        <span class="md-subhead">match</span>
                    </md-card-header-text>
                </md-card-header>

                <!-- Hero Image, one day it should be of the matched user -->
                <img ng-src="{{s_imgPath}}" class="md-card-image" alt="Washed Out">

                <!-- The Card Title -->
                <md-card-title>
                    <md-card-title-text>
                        <span class="md-headline">Your Hack Match</span>
                        <span class="md-subhead">Now reach out! <ng-md-icon icon="rowing"></ng-md-icon></span>
                    </md-card-title-text>
                </md-card-title>

                <!-- Action Buttons -->
                <md-card-actions layout="row" layout-align="start center">
                    <md-button>Profile</md-button>
                    <!-- <md-button>More Info</md-button> -->
                    <md-card-icon-actions>
                        <md-button class="md-icon-button" aria-label="Favorite">
                            <md-icon md-svg-icon="/img/icons/favorite.svg"></md-icon>
                        </md-button>
                        <md-button class="md-icon-button" aria-label="Share">
                            <md-icon md-svg-icon="/img/icons/baseline-share-24px.svg"></md-icon>
                        </md-button>
                    </md-card-icon-actions>
                </md-card-actions>

                <!-- Card Content, more of the match info can go here -->
                <md-card-content>
                    <p>
                        The titles of Washed Out's breakthrough song and the first single from Paracosm share the
                        two most important words in Ernest Greene's musical language: feel it. It's a simple request, as well...
                    </p>
                </md-card-content>
            </md-card>
        </div>
    </md-content>
    
    <h2>Matches that had the same common interests and skills</h2>
    <table style="margin: auto">
        <tr>
            <th>First Name</th>
            <th>Skills that Matched</th>
            <th>What you are both Looking For</th>
        </tr>
        <?php if(isset($data)) {
            foreach($data['combined'] as $match) { ?>
                <tr>
                    <td><?= htmlspecialchars($match['first_name']) ?></td>
                    <td><?= htmlspecialchars($match['skills_matched_str']) ?></td>
                    <td><?= htmlspecialchars($match['look_for_matched_str']) ?></td>
                </tr>
            <?php }
        } ?>
    </table>

    <br><br>
    
    <h2>Skills that matched</h2>
    <table style="margin: auto">
        <tr>
            <th>First Name</th>
            <th>Match Score</th>
            <th>Skills that Matched</th>
            <th>user_type</th>
        </tr>
        <?php if(isset($data)) {
            foreach($data['skills'] as $match) { ?>
                <tr>
                    <td><?= htmlspecialchars($match['first_name']) ?></td>
                    <td><?= htmlspecialchars($match['skill_pct_match']) ?></td>
                    <td><?= htmlspecialchars(implode(', ', $match['skills_matched'])) ?></td>
                    <td><?= htmlspecialchars($match['user_type']) ?></td>
                </tr>
            <?php }
        } ?>
    </table>

    <br><br>
    
    <h2>Common interests that match</h2>
    <table style="margin: auto">
        <tr>
            <th>First Name</th>
            <th>What you are both Looking For</th>
            <th>user_type</th>
        </tr>
        <?php if(isset($data)) {
            foreach($data['look_for']['matches'] as $match) { ?>
                <tr>
                    <td><?= htmlspecialchars($match['m_first_name']) ?></td>
                    <td><?= htmlspecialchars(implode(', ', $match['what_matched'])) ?></td>
                    <td><?= htmlspecialchars($match['m_user_type']) ?></td>
                </tr>
            <?php }
        } ?>
    </table>
</div>

<?php
//<!-- Footer -->
include('templates/layout/footer.php');
//<!-- JavaScript -->
include('templates/layout/js-scripts.php');
?>

</body>
</html>
