<?php
/**
 * Created by PhpStorm.
 * User: Julius Alvarado
 * Date: 5/21/2020
 * Time: 6:59 AM
 */

$appName = "HackMatch.io";

?>


<!DOCTYPE html>

<html lang="en" data-ng-app="hackMatchCloudApp">

<head>
    <meta charset="UTF-8">
    <title>HackMatch.io, Contribute to open source.</title>

    <!-- Angular Material CSS now available via Google CDN; version 1.1.9 used here
   "https://ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.css"-->
    <link rel="stylesheet" href="/ui-match/modules/ngmd-min.css">
    <link rel="stylesheet" href="/ui-match/styles/app.css">

    <!-- ng-cloak -->
    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
            display: none !important;
        }
    </style>
</head>


<body ng-controller="MatchCtrl">
<!-- https://codebuddies.org/images/logo.svg -->
<!--<img src="/img/cb-logo.svg" alt="cb connect" height="80px">-->


<!-- Horizontal sort of Nav Bar -->
<md-toolbar>
    <div class="md-toolbar-tools">
        <h2 flex md-truncate> Hack Match</h2>
        
        <a href="/test/get-matched">
            <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
                Back to Questionnaire
            </md-button>
        </a>
        
        <md-button class="md-fab md-mini md-hue-3 cb-pad5" aria-label="Favorite">
            <ng-md-icon icon="favorite" size="30" fill="#ffffff"></ng-md-icon>
        </md-button>
    </div>
</md-toolbar>

<div layout="column" layout-align="center center" class="hm-about-bg">

    <h1>About Hack Match</h1>
    <div layout="row" layout-padding layout-margin layout-align="center center">
        <p flex="60">The primary mission of Hack Match is to: <br> <strong>Match coders with a mentor, mentee,
                collaborator, or pair programming partner based on common interests.</strong> <br>
            This can be for technical help, career help, business ventures, or friendships</p>
    </div>

    <h1>
        Goals for this open source project:
    </h1>

    <div layout="row" layout-padding layout-margin>
        <ol>
            <li>Learn (learning is endless, so this project will be great to learn from).</li>
            <li>Just have fun while <strong>Building Something Cool ^_^</strong></li>
            <li>Collaborate with people, Coders and Noncoders, Beginners or Experienced. It's all good!</li>
            <li>Try to use PHP for <strong>Artificial Intelligence</strong></li>
        </ol>
    </div>

    <h2>The project started 5-29-2020</h2>
    <div layout="row" layout-padding layout-margin layout-align="center center">
        <p><a href="https://github.com/hack-match/hackmatch">Help build it! (:</a></p>
        <p><a href="https://github.com/ideaguy3d">OS Project Maintainer</a></p>
    </div>
</div>


<?php
//<!-- Footer -->
include('templates/layout/footer.php');
//<!-- JavaScript -->
include('templates/layout/html-lower.php');
?>

</body>
</html>