<!DOCTYPE html>

<html lang="en" data-ng-app="hackMatchCloudApp">

<head>
    <meta charset="UTF-8">
    <title>Julius, Full Stack & Data Engineer</title>

    <!-- Angular Material CSS now available via Google CDN; version 1.1.9 used here
    "https://ajax.googleapis.com/ajax/libs/angular_material/1.1.9/angular-material.min.css"-->
    <link rel="stylesheet" href="/ui-match/modules/ngmd-min.css">
    <link rel="stylesheet" href="/ui-match/styles/demo-styles.css">
    <link rel="stylesheet" href="/ui-match/styles/app.css">

    <!-- ng-cloak -->
    <style type="text/css">
        [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak {
            display: none !important;
        }
    </style>
</head>

<body ng-controller="MatchCtrl">

<!-- tool header -->
<md-toolbar>
    <div class="md-toolbar-tools">
        <h1 flex md-truncate>
            <md-button href="/julius-alvarado">
                <span style="font-size: 18px">Julius Alvarado's <b>Portfolio App</b></span>
            </md-button>
        </h1>

        <a href="/julius/about">
            <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
                About
            </md-button>
        </a>
        <a href="/julius/edu">
            <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
                Education
            </md-button>
        </a>
        <a href="/julius/learn">
            <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
                Learn
            </md-button>
        </a>
        <a href="/CV_Julius-Hernandez-Alvarado.pdf" target="_blank">
            <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
                CV
            </md-button>
        </a>
        <a href="https://linkedin.com/in/juliusalvarado" target="_blank">
            <md-button class="md-raised md-accent md-hue-3 cb-btn" aria-label="Learn More">
                LinkedIn
            </md-button>
        </a>
    </div>
</md-toolbar>

<md-sidenav>

</md-sidenav>