<?php include 'templates/layout/html-upper-jh.phtml'; ?>

<div layout="column" layout-align="center center" class="hm-about-bg">

    <h1>Hello ^_^/</h1>
    <div layout="row" layout-padding layout-margin layout-align="center center">
        <p flex="40">
            I spent a little over 100 hours building hackmatch.io in May/June 2020.
            It was originally a pull request to the
            <a href="https://github.com/codebuddies/cb-connect" target="_blank">CodeBuddies Connect</a> project,
            but wasn't merged. So I made it its' own <i>Open Source</i> organization
        </p>
        <p flex="40">
            Now it's just a project I plan to use for hacking tough engineering problems on, from Artificial
            Intelligence & Data Analysis to Big Data & Cloud Engineering, for fun and learning.
        </p>
    </div>
    
    <br><br><br><br>
</div>


<?php include 'templates/layout/html-lower-jh.phtml'; ?>
