<?php include 'templates/layout/html-upper-jh.phtml'; ?>

<div layout="column" layout-align="center center" class="hm-about-bg">
    
    <h1>About Hack Match</h1>
    <div layout="row" layout-padding layout-margin layout-align="center center">
        <p flex="60">
            The primary mission of Hack Match is to: <br>
            <strong>
                Match coders with a mentor, mentee, collaborator, or
                pair programming partner based on common interests
            </strong> <br>
            This can be for technical help, career help, business ventures, or friendships
        </p>
    </div>

</div>

<?php include 'templates/layout/html-lower-jh.phtml'; ?>
