<?php include 'templates/layout/html-upper-jh.phtml'; ?>

<div layout="column" layout-align="center center" class="hm-about-bg">

    <h1>I am in the process of learning several skills <br></h1>
    <h2 class="cb-mtop-0">1. Expert Level PHP, 2. BigQuery, 3. Laravel/React</h2>

    <div layout="row" layout-padding layout-margin layout-align="center center">
        <h2>1. Expert Level PHP:</h2>
        <p flex="60">
            <small>
                <i>For Sep.2020, This is where 90% of my mental energy is going</i>
            </small>
            <br><br>
            <strong>
                I've been studying for the Zend Certified Engineer exam,
                which is where the idea of building this cloud app came from.
            </strong> <br><br>
            I am spending time memorizing tons of various techniques & global functions in PHP <br>
            and wanted a way to persist the stuff I'm memorizing, just in case my brain forgets stuff.<br>
        </p>
    </div>

    <div layout="row" layout-padding layout-margin layout-align="center center">
        <h2>2. BigQuery:</h2>
        <p flex="60">
            <small>
                <i>Google BigQuery on GCP using the Web UI and the PHP client libraries.<br>
                    I'm not spending too much time on this yet.</i>
            </small>
            <br><br>
            <strong>
                I'm interested in proving that PHP is an excellent tool for
                Data Engineering & Statistical Computing(aka Data Analysis).
            </strong> <br><br>
            Like most people, I never thought of using PHP in these manners. <br>
            But it was all I used PHP for while working at Redstone Print & Mail. <br>
            So I learned how to use PHP for these purposes w/its' sister language, SQL.
        </p>
    </div>

    <div layout="row" layout-padding layout-margin layout-align="center center">
        <h2>3. Laravel/React:</h2>
        <p flex="60">
            <small>
                <i>The web app framework Laravel & The React Web UI framework<br>
                    I'll get to this eventually. Sooner than later.</i>
            </small>
            <br><br>
            <strong>
                Sigh, The industry still perceives PHP for just Web... <br>
                and Python for Data & Web.
            </strong> <br><br>
            So this is the status quo for the PHP world at the moment.
            Hopefully my work will get PHP in the Data world as well.
        </p>
    </div>

    <br><br><br><br>
</div>

<?php include 'templates/layout/html-lower-jh.phtml'; ?>
