<?php include 'templates/layout/html-upper-jh.phtml'; ?>

<div layout="column" layout-align="center center" class="hm-about-bg">

    <h1>My educations' 2 classifications:</h1>
    <h2 class="cb-mtop-0">1. Liberal Arts, 2. Vocational</h2>
    <div layout="row" layout-padding layout-margin layout-align="center center">
        <!-- left side -->
        <h3>1. Liberal Arts education:</h3>

        <!-- right side -->
        <p flex="60">
            This is a bachelors degree <br>
            <small>
                <i><b>
                        Aug.2007-Dec.2012 <br>
                        Institutions: San Joaquin Delta College, San Jose City College, San Jose State University.
                    </b></i>
            </small>
            <br><br>
            <strong>
                Lower-Division is mostly general education (i.e. the liberal arts) <br>
                Upper-Division is what you majored in (but not always practical for industry)
            </strong> <br><br>
            I was always working full time, and going to school part time. After about 6 years I <br>
            think I completed about 90 units of the ~150 units for a B.S. in Computer Science. <br> <br>

            ... Then dropped out to start a company using my game development skills that I learned outside of college.
        </p>
    </div>

    <div layout="row" layout-padding layout-margin layout-align="center center">
        <h3>2. Vocational Education</h3>
        <p flex="60">
            This is <b>practical</b> skills and experience <br>
            <small>
                <i><b>Dec.2012-Present <br>Institution: School of Hard Knocks.</b></i>
            </small>
            <br><br>
            <strong>
                It's 100% aimed for ONLY job skills. And cost me about $0 to $50 a month.
            </strong> <br><br>
            From Dec.2012 to Present, I've spent over 14,000 hours becoming self-taught <br>
            <small>
                <b>(4-7 hours of study&practice per day on average, while working various day jobs.)</b>
            </small> <br><br>
            - 30% of those hours are from 20+ online tech education platforms (pluralsight, coursera, udemy., etc.)<br>
            - 30% of those hours are from studying documentation (php.net, nodejs.org, microsoft/google docs, etc.)<br>
            - 40% of those hours are reading other peoples code, books, and just building stuff.
        </p>
    </div>
    
    <br><br>
</div>

<?php include 'templates/layout/html-lower-jh.phtml'; ?>
